config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "wiki", to: "wiki#index"
  get "wiki/new", to: "wiki#new"

  get "wiki/:id", to: "wiki#show", as: "wikis"
  post "wiki", to: "wiki#create", as: "create_wiki"

  get "/wiki/:id/edit", to: "wiki#edit", as: "edit_article"
  patch "wiki/:id", to: "wiki#update", as: "update_wiki"

  delete "/wiki/:id", to: "wiki#destroy", as: "delete_wiki"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  def index
    @wikis = Article.all
  end

  def show
    @wiki = Article.find(params[:id])
  end

  def new
    @wiki = Article.new
  end

  def create
    @wiki = Article.new(params_wiki)
    @wiki.save
    redirect_to wiki_path(@wikis)
  end

  def params_wiki
    params.require(:article).permit(:title, :content)
  end

  def edit
    @wiki = Article.find(params[:id])
  end

  def update
    @wiki = Article.find(params[:id])
    @wiki.update(params_wiki)
    redirect_to wiki_path(@wiki)
  end

  def destroy
    @wiki = Article.find(params[:id])
    @wiki.destroy
    redirect_to wiki_path(@wiki)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wiki/edit.html.erb
<h1>Edit an existing article</h1>

<%= form_with model: @wiki, url: update_wiki_path do |w| %>
  <%= w.label :title %>
  <%= w.text_field :title %>
    <%= w.label :content %>
  <%= w.text_field :content %>
  <%= w.submit %>
<% end %>

app/views/wiki/index.html.erb
<h1>Article list</h1>

<% @wikis.each do |wik| %>
<li><%=link_to wik.title, wikis_path(wik)%></li>
<% end %>
<%= link_to "Add an Article", wiki_new_path %>

app/views/wiki/new.html.erb
<%= form_with model: @wiki, url: create_wiki_path do |w| %>
  <%= w.label :title %>
  <%= w.text_field :title %>
    <%= w.label :content %>
  <%= w.text_field :content %>
  <%= w.submit %>
<% end %>

app/views/wiki/show.html.erb
<h1>Article Selected</h1>

<h2><%= @wiki.content %></h2>
<%= link_to "Article List", wiki_path %>
<%= link_to "Edit", edit_article_path(@wiki)%><br>
<%= link_to "Delete", delete_wiki_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>